[phases.setup]
nixPkgs = ["python3", "gcc" ]

[phases.install]
commands = [
    "echo 'Setup phase: Installing venv...'",
    "python -m venv --copies /opt/venv && . /opt/venv/bin/activate",
    "pip install -r requirements.txt"
]

[phases.build]
commands = [
    "echo 'Build phase: (No build process specified)'"
]

[start]
cmd = "python bot.py"
